[package]
name = "ferrets-network"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Lockstep P2P networking for deterministic multiplayer."

[dependencies]
bcs.workspace = true
crossbeam-channel.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true

ferrets-math.workspace = true
ferrets-simulation.workspace = true
