//! Per-tick simulation logic: command dispatch and order execution.

pub mod acquire;
pub mod attack;
pub mod attack_move;
pub mod auto_engage;
pub mod board;
pub mod build;
mod cast_cost;
mod chase;
mod crew;
pub mod damage;
pub mod die;
pub mod executor;
pub mod flee;
pub mod follow;
pub mod game_result;
pub mod garrison;
pub mod guard;
pub mod harvest;
pub mod impacts;
pub mod load;
pub mod morph;
pub mod movement;
pub mod orders;
pub mod patrol;
pub mod pending_reveal;
pub mod pushing;
mod rally;
pub mod repair;
pub mod research;
pub mod stats;
pub mod tally;
pub mod tick_counter;
pub mod train;
mod turn;
pub mod turret;
pub mod unload;
pub mod visibility;
mod work;
