[package]
name = "ferrets-replay"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Replay recording and deterministic playback."

[dependencies]
ferrets-geometry.workspace = true
ferrets-simulation.workspace = true

bcs.workspace = true
serde.workspace = true
thiserror.workspace = true
