[workspace.package]
edition = "2024"
version = "0.1.0"
authors = ["Valerii Reutov <valeriy.reutov@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/valeriyr/ferrets"

[workspace]
resolver = "3"
members = [
    "crates/ferrets-bevy-plugin",
    "crates/ferrets-geometry",
    "crates/ferrets-math",
    "crates/ferrets-network",
    "crates/ferrets-pathfinder",
    "crates/ferrets-physics",
    "crates/ferrets-replay",
    "crates/ferrets-script",
    "crates/ferrets-simulation",
    "crates/ferrets-steam",
    "ferrets-demo",
]

[workspace.dependencies]
# External crates
bcs = "0.2"
bevy = { version = "0.18", default-features = false }
crossbeam-channel = "0.5"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
tokio = { version = "1.52", features = ["full"] }

# Internal crates
ferrets-bevy-plugin = { path = "crates/ferrets-bevy-plugin" }
ferrets-geometry = { path = "crates/ferrets-geometry" }
ferrets-math = { path = "crates/ferrets-math" }
ferrets-network = { path = "crates/ferrets-network" }
ferrets-pathfinder = { path = "crates/ferrets-pathfinder" }
ferrets-physics = { path = "crates/ferrets-physics" }
ferrets-replay = { path = "crates/ferrets-replay" }
ferrets-script = { path = "crates/ferrets-script" }
ferrets-simulation = { path = "crates/ferrets-simulation" }
ferrets-steam = { path = "crates/ferrets-steam" }

