[package]
name = "ferrets-demo"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "ferrets demo game."

[[bin]]
name = "demo"
path = "src/main.rs"

[[bin]]
name = "replay"
path = "src/bin/replay.rs"

[dependencies]
bevy = { workspace = true, features = ["2d", "ui", "default_font", "bevy_audio"] }
rfd = "0.17"

ferrets-bevy-plugin.workspace = true
ferrets-content.workspace = true
ferrets-geometry.workspace = true
ferrets-math.workspace = true
ferrets-network.workspace = true
ferrets-physics.workspace = true
ferrets-replay.workspace = true
ferrets-script.workspace = true
ferrets-simulation.workspace = true
