[package]
name = "ferrets-simulation"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Deterministic RTS game simulation."

[dependencies]
bevy_ecs = "0.18"
serde.workspace = true
xxhash-rust = { version = "0.8", features = ["xxh64"] }

ferrets-geometry.workspace = true
ferrets-math.workspace = true
ferrets-pathfinder.workspace = true
ferrets-physics.workspace = true
