[package]
name = "ferrets-bevy"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Bevy integration for the ferrets simulation."

[dependencies]
bevy.workspace = true

ferrets-network.workspace = true
ferrets-replay.workspace = true
ferrets-simulation.workspace = true

[dev-dependencies]
ferrets-math.workspace = true
ferrets-pathfinder.workspace = true
