[package]
name = "ferrets-pathfinder"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Deterministic RTS game pathfinding."

[dependencies]
pathfinding = "4.15"
serde.workspace = true

ferrets-math.workspace = true
