[package]
name = "ferrets-content"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Content vocabulary and registry for the game engine."

[dependencies]
bevy_ecs.workspace = true
serde.workspace = true

ferrets-geometry.workspace = true
ferrets-math.workspace = true
ferrets-pathfinder.workspace = true
