[package]
name = "demo"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "ferrets demo game."

[[bin]]
name = "ferrets"
path = "src/main.rs"

[dependencies]
bevy = { workspace = true, features = ["2d", "ui", "default_font"] }
rfd = "0.17"

ferrets-bevy.workspace = true
ferrets-math.workspace = true
ferrets-network.workspace = true
ferrets-pathfinder.workspace = true
ferrets-replay.workspace = true
ferrets-script.workspace = true
ferrets-simulation.workspace = true
