//! Content vocabulary — type definitions for everything content declares,
//! and the registry that holds them.

pub mod affiliation;
pub mod annex;
pub mod attack;
pub mod berths;
pub mod brood;
pub mod build;
pub mod costs;
pub mod dying;
pub mod entity_buffs;
pub mod entity_stats;
pub mod entity_type_def;
pub mod field;
pub mod kinds;
pub mod location;
pub mod morph;
pub mod player_buffs;
pub mod player_stats;
pub mod projectile;
pub mod quantity;
pub mod registry;
pub mod repair;
pub mod requirement;
pub mod research;
pub mod resource;
pub mod selection;
pub mod skills;
pub mod splash;
pub mod stack_rule;
pub mod stand;
pub mod stats;
pub mod tags;
pub mod targeting;
pub mod train;
pub mod transport;
pub mod turret;
pub mod work;
